class Estoque: # A classe Estoque é responsável por gerenciar os produtos em um estoque. Ela possui um atributo privado __produtos, que é uma lista que armazena os produtos. A classe também possui métodos públicos para adicionar produtos ao estoque e listar os produtos presentes no estoque.
    def __init__(self): # Construtor para inicializar o estoque, criando uma lista vazia para armazenar os produtos. O atributo __produtos é privado, indicando que ele não deve ser acessado diretamente de fora da classe, promovendo o encapsulamento.
        self.__produtos = [] # Atributo privado para armazenar os produtos, utilizando uma lista para permitir a adição de múltiplos produtos ao estoque.

    def adicionar_produto(self, produto): # Método para adicionar um produto ao estoque, recebe um objeto produto como parâmetro e o adiciona à lista de produtos. Este método é público, permitindo que seja chamado de fora da classe para adicionar produtos ao estoque.
        self.__produtos.append(produto)

    def listar_produtos(self): # Método para listar os produtos presentes no estoque, percorre a lista de produtos e chama o método mostrar para cada um.
        for produto in self.__produtos: # Percorre a lista de produtos, utilizando um loop for para iterar sobre cada produto presente no estoque.
            produto.mostrar() # Chama o método mostrar para cada produto, permitindo que as informações de cada produto sejam exibidas. Este método é público, permitindo que seja chamado de fora da classe para listar os produtos presentes no estoque.
    
    def deletar_produto(self, produto): # Método para deletar um produto do estoque, recebe um objeto produto como parâmetro e o remove da lista de produtos, caso ele esteja presente. Este método é público, permitindo que seja chamado de fora da classe para remover produtos do estoque.
        if produto in self.__produtos: # Verifica se o produto está presente na lista de produtos, utilizando uma estrutura condicional if para garantir que o produto só seja removido se ele realmente existir no estoque.
            self.__produtos.remove(produto) # Remove o produto da lista de produtos, utilizando o método remove para eliminar o produto do estoque. Este método é público, permitindo que seja chamado de fora da classe para remover produtos do estoque.
    
    def atualizar_produto(self, produto_antigo, produto_novo): # Método para atualizar um produto no estoque, recebe dois objetos produto como parâmetros: o produto antigo que deve ser atualizado e o produto novo que contém as informações atualizadas. O método verifica se o produto antigo está presente na lista de produtos e, se estiver, substitui-o pelo produto novo. Este método é público, permitindo que seja chamado de fora da classe para atualizar produtos no estoque.
        if produto_antigo in self.__produtos: # Verifica se o produto antigo está presente na lista de produtos, utilizando uma estrutura condicional if para garantir que a atualização só ocorra se o produto antigo realmente existir no estoque.
            index = self.__produtos.index(produto_antigo) # Obtém o índice do produto antigo na lista de produtos, utilizando o método index para localizar a posição do produto antigo na lista.
            self.__produtos[index] = produto_novo # Substitui o produto antigo pelo produto novo na lista de produtos, utilizando o índice obtido para realizar a substituição. Este método é público, permitindo que seja chamado de fora da classe para atualizar produtos no estoque.
    
    def entrada_produto(self, produto, quantidade): # Método para registrar a entrada de um produto no estoque, recebe um objeto produto e a quantidade que está entrando. O método verifica se o produto está presente na lista de produtos e, se estiver, atualiza a quantidade atual do produto somando a quantidade que está entrando. Este método é público, permitindo que seja chamado de fora da classe para registrar a entrada de produtos no estoque.
        if produto in self.__produtos: # Verifica se o produto está presente na lista de produtos, utilizando uma estrutura condicional if para garantir que a entrada só seja registrada se o produto realmente existir no estoque.
            index = self.__produtos.index(produto) # Obtém o índice do produto na lista de produtos, utilizando o método index para localizar a posição do produto na lista.
            self.__produtos[index].quantidade_atual += quantidade # Atualiza a quantidade atual do produto somando a quantidade que está entrando, utilizando o índice obtido para acessar o produto na lista e atualizar seu atributo quantidade_atual. Este método é público, permitindo que seja chamado de fora da classe para registrar a entrada de produtos no estoque.
    
    def saida_produto(self, produto, quantidade): # Método para registrar a saída de um produto do estoque, recebe um objeto produto e a quantidade que está saindo. O método verifica se o produto está presente na lista de produtos e, se estiver, verifica se a quantidade atual do produto é suficiente para realizar a saída. Se for suficiente, atualiza a quantidade atual do produto subtraindo a quantidade que está saindo. Caso contrário, exibe uma mensagem indicando que a quantidade em estoque é insuficiente para realizar a saída. Este método é público, permitindo que seja chamado de fora da classe para registrar a saída de produtos do estoque.
        if produto in self.__produtos: # Verifica se o produto está presente na lista de produtos, utilizando uma estrutura condicional if para garantir que a saída só seja registrada se o produto realmente existir no estoque.
            index = self.__produtos.index(produto) # Obtém o índice do produto na lista de produtos, utilizando o método index para localizar a posição do produto na lista.
            if self.__produtos[index].quantidade_atual >= quantidade: # Verifica se a quantidade atual do produto é suficiente para realizar a saída, utilizando uma estrutura condicional if para comparar a quantidade atual do produto com a quantidade que está saindo.
                self.__produtos[index].quantidade_atual -= quantidade # Atualiza a quantidade atual do produto subtraindo a quantidade que está saindo, utilizando o índice obtido para acessar o produto na lista e atualizar seu atributo quantidade_atual. Este método é público, permitindo que seja chamado de fora da classe para registrar a saída de produtos do estoque.
            else: # Caso contrário, exibe uma mensagem indicando que a quantidade em estoque é insuficiente para realizar a saída, utilizando uma estrutura condicional else para lidar com a situação em que a quantidade atual do produto é menor do que a quantidade que está saindo.
                print("Quantidade insuficiente em estoque para realizar a saída.") # Exibe uma mensagem de erro indicando que a quantidade em estoque é insuficiente para realizar a saída, informando ao usuário sobre a situação. Este método é público, permitindo que seja chamado de fora da classe para registrar a saída de produtos do estoque.

# Da linha 1 até a linha 10, o código contempla:
# 1. Encapsulamento (através do uso de atributos privados - linha 3 - e métodos públicos para manipular esses atributos - linhas 5, 8, 12, 16, 21 e 26),
# 2. Abstração (a classe Estoque - linha 1 - define uma interface para gerenciar os produtos, ocultando os detalhes de implementação do armazenamento dos produtos) e
# 3. Polimorfismo (o método mostrar - linha 10 - é chamado para cada produto, permitindo que diferentes tipos de produtos possam ser listados sem a necessidade de conhecer suas implementações específicas).