from produto import Bebida, Produto, ProdutoPerecivel # Importação das classes de produtos, incluindo a classe base Produto e as subclasses ProdutoPerecivel e Bebida, que representam tipos específicos de produtos com características adicionais.
from usuario import cozinha, estoquista, admin # Importação das classes de usuários, incluindo a classe base Usuario e as subclasses cozinha, estoquista e admin, que representam tipos específicos de usuários com permissões diferentes.
from unidade import Unidade # Importação da classe Unidade, que define as unidades de medida utilizadas para os produtos, utilizando a estrutura de enumeração para garantir a consistência e facilitar o uso das unidades de medida em todo o sistema.
from estoque import Estoque # Importação da classe Estoque, responsável por gerenciar os produtos em um estoque, permitindo adicionar, listar, deletar, atualizar, registrar entrada e saída de produtos.

estoque = Estoque() # Criação de uma instância da classe Estoque, que será utilizada para gerenciar os produtos em nosso sistema, permitindo adicionar, listar, deletar, atualizar, registrar entrada e saída de produtos. Esta instância do estoque servirá como o repositório central para armazenar e manipular os produtos disponíveis no sistema.


produto1 = Bebida("Refrigerante", "Bebida", 10, Unidade.LITRO, 10, "2025-12-31", 2) # Criação de uma instância da classe Bebida, representando um produto do tipo bebida, com atributos específicos como nome, categoria, quantidade, unidade de medida, quantidade mínima, data de validade e quantidade unitária. Esta instância do produto do tipo bebida será adicionada ao estoque para gerenciamento e controle das bebidas disponíveis no sistema.
produto2 = ProdutoPerecivel("Queijo Cheddar", "Laticínio", 10, Unidade.QUILO, 10, "2026-05-30") # Criação de uma instância da classe ProdutoPerecivel, representando um produto com validade, com atributos específicos como nome, categoria, quantidade, unidade de medida, quantidade mínima e data de validade. Esta instância do produto com validade será adicionada ao estoque para gerenciamento e controle dos produtos perecíveis disponíveis no sistema.
produto3 = Produto("Arroz", "Grãos", 20, Unidade.QUILO, 10, "2027-01-15") # Criação de uma instância da classe Produto, representando um produto genérico, com atributos como nome, categoria, quantidade, unidade de medida, quantidade mínima e data de validade. Esta instância do produto genérico será adicionada ao estoque para gerenciamento e controle dos produtos disponíveis no sistema.

estoque.adicionar_produto(produto1) # Adição do produto do tipo bebida ao estoque, utilizando o método adicionar_produto da classe Estoque para incluir a instância do produto do tipo bebida no estoque, permitindo que ele seja gerenciado e controlado dentro do sistema.
estoque.adicionar_produto(produto2) # Adição do produto com validade ao estoque, utilizando o método adicionar_produto da classe Estoque para incluir a instância do produto com validade no estoque, permitindo que ele seja gerenciado e controlado dentro do sistema.
estoque.adicionar_produto(produto3) # Adição do produto genérico ao estoque, utilizando o método adicionar_produto da classe Estoque para incluir a instância do produto genérico no estoque, permitindo que ele seja gerenciado e controlado dentro do sistema.

usuario1 = cozinha("Carlos") # Criação de uma instância da classe cozinha, representando um usuário do tipo cozinha, com o nome "Carlos". Esta instância do usuário do tipo cozinha terá permissões específicas para acessar o estoque, permitindo que ele visualize os produtos disponíveis, mas com acesso limitado ao controle operacional do estoque. O usuário do tipo cozinha é responsável por acessar o estoque para verificar os produtos disponíveis e suas quantidades, mas não tem permissão para realizar operações de controle operacional, como adicionar ou remover produtos do estoque.
usuario2 = estoquista("Ana") # Criação de uma instância da classe estoquista, representando um usuário do tipo estoquista, com o nome "Ana". Esta instância do usuário do tipo estoquista terá permissões específicas para acessar o estoque, permitindo que ele controle operacionalmente o estoque, incluindo a entrada, saída e listagem de produtos, mas com acesso limitado às informações do estoque. O usuário do tipo estoquista é responsável por gerenciar o estoque, realizando operações de controle operacional para garantir que os produtos estejam organizados e disponíveis para uso, mas não tem permissão para acessar todas as informações do estoque.
usuario3 = admin("Maria") # Criação de uma instância da classe admin, representando um usuário do tipo admin, com o nome "Maria". Esta instância do usuário do tipo admin terá permissões completas para acessar e manipular o estoque, incluindo todas as operações de controle operacional. O usuário do tipo admin é responsável por gerenciar o estoque de forma completa, tendo acesso a todas as informações e funcionalidades do sistema.

usuario1.mostrar_permissao() # Chamada do método mostrar_permissao para o usuário do tipo cozinha, exibindo as permissões específicas associadas a esse tipo de usuário, que incluem acesso limitado ao estoque. Esta chamada do método permite que o usuário do tipo cozinha visualize suas permissões e entenda as limitações de acesso ao estoque, garantindo que ele saiba quais operações pode realizar dentro do sistema.
usuario2.mostrar_permissao() # Chamada do método mostrar_permissao para o usuário do tipo estoquista, exibindo as permissões específicas associadas a esse tipo de usuário, que incluem controle operacional do estoque. Esta chamada do método permite que o usuário do tipo estoquista visualize suas permissões e entenda as responsabilidades de controle operacional do estoque, garantindo que ele saiba quais operações pode realizar dentro do sistema para gerenciar o estoque de forma eficiente.
usuario3.mostrar_permissao() # Chamada do método mostrar_permissao para o usuário do tipo admin, exibindo as permissões específicas associadas a esse tipo de usuário, que incluem acesso total ao sistema. Esta chamada do método permite que o usuário do tipo admin visualize suas permissões e entenda que ele tem acesso completo a todas as funcionalidades do sistema, garantindo que ele saiba quais operações pode realizar dentro do sistema para gerenciar o estoque de forma abrangente.

estoque.listar_produtos() # Chamada do método listar_produtos para o estoque, exibindo a lista de produtos presentes no estoque, incluindo o produto do tipo bebida, o produto com validade e o produto genérico. Esta chamada do método permite que os usuários visualizem os produtos disponíveis no estoque, suas quantidades e outras informações relevantes, facilitando a gestão e controle dos produtos dentro do sistema.


# Da linha 1 até a linha 4, o código contempla:
# 1. Importação de módulos e classes (importação das classes de produtos, usuários, unidades e estoque, permitindo o uso dessas classes em nosso código para criar instâncias e manipular os objetos relacionados a produtos, usuários e estoque).
# Da linha 9 até a linha 23, o código contempla:
# 1. Criação de instâncias (criação de instâncias de produtos e usuários, permitindo a representação de produtos específicos e usuários com diferentes permissões dentro do sistema).
# A linha 25 chama o método listar_produtos para o estoque, exibindo a lista de produtos presentes no estoque, incluindo o produto do tipo bebida, o produto com validade e o produto genérico. Esta chamada do método permite que os usuários visualizem os produtos disponíveis no estoque, suas quantidades e outras informações relevantes, facilitando a gestão e controle dos produtos dentro do sistema.